version: '3.8'
services:
    product:
        build:
            context: ./apps/ms-product
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        networks:
            - app
    photo:
        build:
            context: ./apps/ms-photo
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        networks:
            - app
    inventory:
        build:
            context: ./apps/ms-inventory
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        networks:
            - app
    review:
        build:
            context: ./apps/ms-review
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        networks:
            - app
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/sites/:/etc/nginx/conf.d/
        depends_on:
            - product
            - photo
            - inventory
            - review
        networks:
            - app
networks:
    app:
        driver: bridge