version: '3.8'
services:
    product:
        build:
            context: ./apps/ms-product
            dockerfile: Dockerfile
        restart: unless-stopped
        # environment:
        #     - DB_HOST=host.docker.internal
        volumes:
            - ./apps/ms-product:/var/www/html
        tty: true
        networks:
            - app
    photo:
        build:
            context: ./apps/ms-photo
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./apps/ms-photo:/var/www/html
        tty: true
        networks:
            - app
    inventory:
        build:
            context: ./apps/ms-inventory
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./apps/ms-inventory:/var/www/html
        tty: true
        networks:
            - app
    review:
        build:
            context: ./apps/ms-review
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./apps/ms-review:/var/www/html
        tty: true
        networks:
            - app
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/sites/:/etc/nginx/conf.d/
        depends_on:
            - product
            - photo
            - inventory
            - review
        networks:
            - app

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        ports:
        - '8080:80'
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: passwd
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8-oracle'
        restart: unless-stopped
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_USER: rd
            MYSQL_PASSWORD: rdrd
            MYSQL_DATABASE: poc_system
            MYSQL_ROOT_PASSWORD: passwd

networks:
    app:
        driver: bridge
volumes:
    mysql-data: null